### ISSUE TITLE
nanojson could use a more active maintainer

### ISSUE THREAD

**Issue by mmastrac** [mmastrac/nanojson#11]
I haven't had much time to work on the library recently, but I've merged my `JsonReader` branch in and the codebase is in good shape. If anyone is interested in taking over, please let me know.

**Comment by cyanobacterium** [comment]
Hi mmtrac!

As you can see, I'm not so active, either, but I'm willing to take it on. This library is my go-to for JSON in Java and I've been using a modified local copy setup for modular java anyway.

Cheers,
-Chris

**Comment by mmastrac** [comment]
Added you as a collaborator. I trust you will use those powers for good and not evil. :)

Thanks for helping out!
