### ISSUE TITLE
Add 'Automatic-Module-Name' to MANIFEST.MF to support Java 9+ modules

### ISSUE THREAD

**Issue by ccavanaugh** [mmastrac/nanojson#28]
Please consider adding **Automatic-Module-Name** to the manifest file,  This should be easily handled within Maven.  This won't force use of Java 9+, but improve ease of use with it.

**Comment by mmastrac** [comment]
@ccavanaugh Thanks for the issue report! I have not been working in Java a lot these days, so feel free to drop a PR in. I will usually merge them if they build cleanly.

**Comment by cyanobacterium** [comment]
I'm adding that now. Module name will be **com.grack.nanojson**

I'm also working on an update to JDK 11 since that's the current LTS java version. However, doing so will break compatibility with Java 7 (current target), so that may warrant bumping to version 2.0 when it happens.

**Comment by cyanobacterium** [comment]
Done! See #30
