### ISSUE TITLE
Test failures in https://github.com/nst/JSONTestSuite

### ISSUE THREAD

**Issue by iloveeclipse** [mmastrac/nanojson#3]
Main article: http://seriot.ch/parsing_json.html
Results for nanojson: http://seriot.ch/json/parsing.html#20

**Comment by mmastrac** [comment]
Thanks! I'll add those tests internally and fix them. Looks like they are all around trailing decimals in numbers and a likely missing UTF8 check.

**Comment by iloveeclipse** [comment]
Thanks, that was fast!

**Comment by mmastrac** [comment]
Appreciate the report. If you're interested, I created issue #4 for getting a proper 1.1 maven release out with these fixes.

**Comment by electrum** [comment]
Note that the current link is here: https://seriot.ch/projects/parsing_json.html
