### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wb9688** [mmastrac/nanojson#38]
I get an ArrayIndexOutOfBoundsException when trying to parse [this JSON](https://github.com/mmastrac/nanojson/files/4488259/a.json.txt).

**Comment by mmastrac** [comment]
Thanks for the repro. I can definitely get to fixing this. Looks like a buffer edge case.

**Comment by mmastrac** [comment]
Released as 1.5
