### ISSUE TITLE
Make keys preserve ordering in JsonObject

### ISSUE THREAD

**Issue by dweiss** [mmastrac/nanojson#43]
Great project, @mmastrac - thank you for sharing it. I eyeballed the code and have a few minor nitpicks that I can file as a PR if you're interested. One major change that I made locally is to make JsonObject extend LinkedHashMap instead of HashMap. This allows deserialized objects to retain key ordering which is sometimes useful. What do you think?

**Comment by mmastrac** [comment]
> One major change that I made locally is to make JsonObject extend LinkedHashMap instead of HashMap

I think that should be fine. Feel free to PR it!

**Comment by dweiss** [comment]
Filed #44
