### ISSUE TITLE
Bump minimum Java to Java 8?

### ISSUE THREAD

**Issue by dweiss** [mmastrac/nanojson#46]
This would result in a number of simplified code paths (where you could use getOrDefault, standard charsets, etc.). I'm even tempted to say switch directly to Java 11 as the minimum but since it's such a compact, self-contained project Java 8 seems like a reasonable switch?

**Comment by mmastrac** [comment]
That works for me. I think Java 8 is a reasonable target and Android was mainly the thing holding us back.

**Comment by dweiss** [comment]
Thanks! I'll go through the code in a spare minute and replace as many things as I can see.

**Comment by dweiss** [comment]
I filed a PR here. https://github.com/mmastrac/nanojson/pull/47

I also noticed the current get(key, default) methods are not really possible to replace with getOrDefault because they currently return the default value if the existing value exists but is not of the right type. I don't know what the rationale for this was but it seems a bit trappy to me. Say, when you're parsing something and use getOrDefault then there is a possibility of passing an invalid input (with a key value of incorrect type) resulting in a silent replacement for the default, without any side-effects.

**Comment by mmastrac** [comment]
> Say, when you're parsing something and use getOrDefault then there is a possibility of passing an invalid input (with a key value of incorrect type) resulting in a silent replacement for the default, without any side-effects.

The original design for this was that the parser should be able to traverse any provided JSON without throwing exceptions (although returning null in cases if no default was provided). 

While I still like this guarantee for the `get` methods, I think we could choose a few options to provide a non-swallowing API (roughly most to least favourable in my view):

 - The caller could instruct the reader at construction time not to swallow improperly-typed values and throw a `ClassCastException` instead (my preference). If we leave the default to swallow those cast exceptions, that would be backwards-compatible.
 - Parallel getter methods could be provided
 - Provide a callback where any potential class-cast exceptions could be passed in for handling and/or fixing up.

**Comment by dweiss** [comment]
Ok, fair enough. This didn't look like an oversight - that's why I asked. It can stay as it is, actually. I just found it mildly surprising because I typically prefer things to be the other way around -- break eagerly rather than be lenient. I've spent a great many hours debugging and trying to figure out what's going on when an important exception was quietly swallowed and ignored deep somewhere...

**Comment by mmastrac** [comment]
Going to close this issue because nanojson now has a minimum required version of Java 8. Thanks for the help!
