### ISSUE TITLE
Add a benchmark to https://github.com/fabienrenaud/java-json-benchmark

### ISSUE THREAD

**Issue by iloveeclipse** [mmastrac/nanojson#5]
Would be nice if you could contribute to the https://github.com/fabienrenaud/java-json-benchmark so thatthe nanojson can be compared with other parsers.

**Comment by mmastrac** [comment]
Good idea. I've got my own internal benchmarks, but I haven't updated them for a while.

**Comment by fabienrenaud** [comment]
nanojson is now part of the benchmark.
I have just published the results: https://github.com/fabienrenaud/java-json-benchmark

**Comment by mmastrac** [comment]
Marking fixed as this is benchmarked - still need to work on perf.
