### ISSUE TITLE
Writing of lazy numbers

### ISSUE THREAD

**Issue by k1w1m8** [mmastrac/nanojson#68]
I was looking for a json parser/formatter which can format JSON without normalizing numbers. It could be useful for test frameworks where we want to format json to make it human readable but with a minimum of other changes. For example, trailing decimal places would be preserved.

I thought maybe nanojson with lazy numbers could do that. 

```
	@Test
	public void testTrailingDecimalLazy() throws JsonParserException {
		Object value = JsonParser.any().withLazyNumbers().from("1.000");
		String json = JsonWriter.string().value(value).done();
		assertEquals("1.000", json);
	}
```

Unfortunately, lazy numbers do not work with JsonWriter. Rather than "1.000", I get "com.grack.nanojson.JsonLazyNumber@18bf3d14".  Seems toString() method is missing in JsonLazyNumber.

Is this intentional or accidental? If accidental, can it be added?

**Comment by mmastrac** [comment]
I think it's just something I neglected to add. Patches welcome!

**Comment by mmastrac** [comment]
FWIW, I think this only requires adding `toString` to `JsonLazyNumber`.

**Comment by k1w1m8** [comment]
Indeed, the above test passed when I added it.

Do you want me to create a PR for it?

**Comment by mmastrac** [comment]
Yes, please. I'll merge it and release a new version.
