### ISSUE TITLE
com.grack.nanojson.JsonLazyNumber should implement toString() like other java.lang.Number classes

### ISSUE THREAD

**Issue by hshafie** [mmastrac/nanojson#77]
Hello,

Unlike other java.lang.Number classes, com.grack.nanojson.JsonLazyNumber does not implement toString(), which poses a problem when serializing back to JSON a Java object obtained by parsing its JSON form. 

Example: parse "[1,2.0,3.14]" as a JsonArray and serialize it back using JsonWriter.string(Object) and you'll get something like "[com.grack.nanojson.JsonLazyNumber@HHH,com.grack.nanojson.JsonLazyNumber@HHH,com.grack.nanojson.JsonLazyNumber@HHH]".

This is the only problem I found after using nanojson for  more than a year. I like it very much: tiny, stable, reliable, documented, no dependencies. We currently use it in  XMLmind XML Editor, a commercial product.

Thank you very much for your great software component!

**PS:** A non-essential feature request. JsonWriter.string(Object) and its likes could support generating indented strings. Not for production use of course, but useful when testing and debugging.

**Comment by adriantodt** [comment]
This already has been implemented and merged in #74, but a new version wasn't released yet.

Pinging @mmastrac, perhaps we should release a new version with it?

**Comment by mmastrac** [comment]
I'll take a look at cutting a new release today. Thanks for the report and ping, @adriantodt

**Comment by mmastrac** [comment]
1.8 has been released, with fix for #74 included. I'd love to add perms for others to release versions of the library but I honestly have no idea how to do so!

```
<dependency>
  <groupId>com.grack</groupId>
  <artifactId>nanojson</artifactId>
  <version>1.8</version>
</dependency>
```

**Comment by mmastrac** [comment]
@hshafie Note that we do actually support indenting using this fluent syntax:

```
JsonWriter.indent("  ")...
```

**Comment by hshafie** [comment]
Downloaded 1.8. Tested it. Problem solved. Thanks.

About JsonWriter.indent("  "). This is neat. I'm sorry I did not spot this method in the javadoc. Thanks again.

Cheers.
