### ISSUE TITLE
Expose JsonWriterBase#preValue(java.lang.String)

### ISSUE THREAD

**Issue by Tillerino** [mmastrac/nanojson#89]
Hi there,

would you be open to somehow exposing the `preValue(java.lang.String)` method of `JsonWriterBase`? The context is the following:

Suppose that you wanted to split up serialization of your objects into multiple methods that can be reused. Let's say you have classes `A` and `B`:

```java
class A {
  B b;
  // ...
}
class B {
  int c;
}
```

If I wanted to extract serialization of `B` into its own method, I'd have to write something like:

```java
void writeA(A a, JsonSink sink) {
  sink.object();
  sink.object("b");
  writeB(sink);
  sink.end();
  sink.end();
}
void writeB(B b, JsonSink sink) {
  sink.value("c", b.c);
}
```

I need to provide a value when specifying a field name, so I need to write the object marker of `B` outside of `writeB`. This means that `writeB` cannot be used as a standalone method. What would fix that is exposing the `preValue` method, e.g. through a `field` method:

```java
void writeA(A a, JsonSink sink) {
  sink.object()
  sink.field("b");
  writeB(sink);
  sink.end();
}
void writeB(B b, JsonSink sink) {
  sink.object()
  sink.value("c", b.c)
  sink.end();
}
```

Cheers

**Comment by mmastrac** [comment]
That would work, happy to accept a PR!
